### ISSUE TITLE
Setup API with basic auth fails

### ISSUE THREAD

**Issue by mauricerenck** [syncwithtech/radar-release#1]
Setting up an API endpoint with basic auth fails on Mac OS with a blank screen.

Mac OS 11.5 and Mac OS 11.6
Radar 1.0.4

**Steps to reproduce:**

- create a new entry
- enter a name
- enter url
- click on authorization
- enter (in my case) email and password
- click next

**Issue:**

A white screen is shown, no errors or ui visible
Hitting cmd+r to reload will show the app with all entries
The new endpoint is also available in the list but doesn't show data in a case where you need to modify the javascript part

Trying to edit the javascript fails, because after hitting "next" on the initial edit screen, again results in a white screen.

This worked in previous versions of the app.

**Comment by vicke4** [comment]
Is this still valid?

**Comment by mauricerenck** [comment]
Yes, this is still valid with version 2.0.0

**Comment by vicke4** [comment]
I've released an update. Can you check if it's fixed?

**Comment by mauricerenck** [comment]
This is working now - thank you :)
