### ISSUE TITLE
access previous state

### ISSUE THREAD

**Issue by mauricerenck** [syncwithtech/radar-release#3]
When customizing notifications, is it possible to access the prev state?

This would allow to only send a notification if the primaryValue changed. This is interessting for things like open issues or pending comments. I want to be alarmed once the value is greater x and then again if the value rises again. This way I won't be notified every for example 5 minutes.

**Comment by vicke4** [comment]
Released in [v2.2.0](https://github.com/syncwithtech/radar-release/releases/tag/v2.2.0).
